# Generated by Django 4.1.3 on 2022-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reting_author',
            field=models.SmallIntegerField(default=0),
        ),
    ]
