# Generated by Django 4.1.3 on 2022-11-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_reting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reting',
            field=models.SmallIntegerField(default=0),
        ),
    ]
