# Generated by Django 4.1.3 on 2022-11-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_reting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reting',
        ),
    ]
