# Generated by Django 4.1.3 on 2022-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_reting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostCategory',
            field=models.ManyToManyField(related_name='news', through='news.PostCategory', to='news.category'),
        ),
    ]
